version: '3.9'
services:

  app:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    command: [ "sh", "-c", "/myapp/bin/migrate up && /myapp/bin/api" ]
    restart: always

  db:
    image: yobasystems/alpine-mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: myapp_root_pass
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: myapp_user
      MYSQL_PASSWORD: myapp_pass
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pmyapp_root_pass" ]
      interval: 3s
      timeout: 5s
      retries: 5
    ports:
      - 3306:3306
    restart: always